[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@selfxyz/contracts/=lib/self-contracts/"]

# Celo Sepolia (Testnet) Configuration
[rpc_endpoints]
celo_sepolia = "https://alfajores-forno.celo-testnet.org"
celo_mainnet = "https://forno.celo.org"

# Etherscan verification
[etherscan]
celo_sepolia = { key = "${CELOSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }
celo_mainnet = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
